name: Lua lint

on:
  push:
    paths: |
      _extensions/titlepage/**
  pull_request:
    paths: |
      _extensions/titlepage/**

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: sudo apt-get update && sudo apt-get install -y luacheck
      - name: Run luacheck
        run: luacheck _extensions/titlepage/*.lua
